apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: novapay-core
  namespace: production
spec:
  replicas: 5
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: novapay-vservice
            routes:
              - primary
      steps:
        - setWeight: 2
        - pause: { duration: 5m }
        - setWeight: 10
        - pause: { duration: 10m }
        - setWeight: 25
        - pause: { duration: 10m }
        - setWeight: 50
        - pause: { duration: 10m }
        - setWeight: 100
      analysis:
        templates:
          - templateName: success-rate-and-latency
        args:
          - name: service-name
            value: novapay-core
  selector:
    matchLabels:
      app: novapay-core
  template:
    metadata:
      labels:
        app: novapay-core
    spec:
      containers:
        - name: novapay-core
          image: novapay/core:1.0.0-REPLACE_WITH_GIT_SHA
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            privileged: false
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"