
name: Novapay CI-CD pipeline

on:
  push:
    branches:
      - main

jobs:
  # Stage 1 & 2: Build & Unit Test
  build-and-test:
    name: "Stage 1 & 2: Build & Unit Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run build and unit tests
        run: ./gradlew build test
